{% set version = "0.5.1" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: 3f59c1b5c469487f399978014f6b3be978683b723595a3a9432a723a43e693d0

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  host:
    - python
    - pip
    - param >=1.9.0
    - pyct >=0.4.4
    - setuptools >=30.3.0
    - nodejs >=9.11.1
  run:
    - bokeh >=1.1.0
    - param >=1.9.0
    - pyviz_comms >=0.7.2
    - markdown
    - pyct >=0.4.4
    - testpath <0.4


test:
  imports:
    - panel

about:
  home: https://panel.pyviz.org
  summary: A high-level Python toolkit for composing widgets and plots
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
